### ISSUE TITLE
App won't start and exits with code 173

### ISSUE THREAD

**Issue by ianhlavats** [swisspol/CompareFolders#32] opened 2017-10-27 16:02 UTC
Hello,

I purchased the pro version and was comparing two large drives. It was taking too long, so I wanted to stop to try again on a pair of subfolders, but the app wouldn't stop so I had to force quit. When I tried to restart it, the app complained it was damaged and I should reinstall from App Store. I deleted the app and tried to reinstall from the App Store, but got the same errors, so I used another "app cleaner" application to try to uninstall all remaining files, then reinstalled from the App Store and restarted my computer. Now Compare Folders keeps trying to start, but crashes immediately and I see the following error in the console:

com.apple.xpc.launchd[1] (net.pol-online.compare-folders.27572[1467]): Service exited with abnormal code: 173

Can you help?

Thanks.

**Comment by swisspol** [comment] 2017-10-28 01:03
Hi! Seems to be a Mac App Store problem: I found some other people reporting such issues:
- http://osxdaily.com/2016/02/29/fix-mac-app-store-apps-not-opening-crashing-error-173/
- https://apple.stackexchange.com/questions/227739/why-have-my-apps-from-the-store-suddenly-started-exiting-with-code-173

There's more information here as well:
https://developer.apple.com/support/certificates/expiration/index.html

> Mac App Store purchases failing to launch.
In some scenarios, an app purchased from the Mac App Store that utilizes receipt validation may fail to launch (exiting with a 173 error code) since it considers a local receipt that includes the expired WWDR Intermediate certificate invalid. OS X regards the receipt as valid when the updated WWDR Intermediate is present on your system and therefore does not request an updated receipt for the application.
To resolve this issue, delete the renewed, non-expired WWDR Intermediate certificate from your System and/or Login keychain within the Keychain Access application. After re-launching the application, you will be prompted for your Mac App Store login credentials in order to obtain a new receipt for the application. After you have launched your application and obtained a valid receipt, you can re-install the renewed certificate to continue your development. This issue will be fixed in a forthcoming update to OS X El Capitan.

**Comment by swisspol** [comment] 2017-10-28 01:04
More info from that same Apple technote:
> Users running OS X El Capitan (v10.11 or v10.11.1) may receive a notification that your Mac app is damaged if it utilizes receipt validation to request a new receipt from Apple. They can resolve this issue by restarting their Mac or updating to OS X El Capitan (v10.11.2) or later.
Mac App Store customers running OS X Snow Leopard (v10.6.8) will be unable to purchase new apps or run previously purchased apps that utilize receipt validation until they install the Mac App Store Update for OS X Snow Leopard which is available via OS X Software Update.

**Comment by swisspol** [comment] 2017-10-28 01:05
Also version 1.2.1 of Compare Folders was uploaded to the Mac App Store on Sep 05, 2017, so it's very recent and has to be signed with the latest Apple certificates.

**Comment by duncandisorderly** [comment] 2017-11-01 19:39
I'm running 10.10.5 on a mac pro, & going beyond that OS isn't an option. restarting the machine doesn't resolve this either.
can you point users to the location of the receipt that needs deleting? searching for wwdr or poking around in the keychain hasn't turned up anything that looks positively unambiguously like the culprit here- a bit of guidance would be nice!
d.

**Comment by swisspol** [comment] 2017-11-02 16:00
Here's something worth trying:

Launch Keychain Access and in View menu, choose "Show Expired Certificates"

![image](https://user-images.githubusercontent.com/627915/32335724-be9da352-bfaa-11e7-818e-c1c97feecb43.png)

Then select Certificates category:

![image](https://user-images.githubusercontent.com/627915/32336307-2c254604-bfac-11e7-81d3-a57a778fe74b.png)

And look for any certificate that would be red i.e. expired. Select and delete them.

Finally restart your Mac, delete and redownload the app from Mac App Store and try launching it.

**Comment by swisspol** [comment] 2017-11-02 17:39
I'm completely at loss regarding what is happening. I verified that everything appears correct in the Apple developer center: all the certificates are valid until August 2018. The in-app purchase is still marked as approved and valid.

The only thing I'm trying right now is to re-build Compare Folders with latest Xcode 9.1 and re-submit to App Store. That will be version 1.2.2 available as soon as it's been reviewed.

**Comment by ianhlavats** [comment] 2017-11-02 19:56
Thanks for your follow ups. I had multiple problems with macOS 10.13 (High Sierra) due to APFS, FileVault, pending Time Machine backups, local snapshots that wouldn't go away and took up all my disk space, immutable files/folders, kernel extensions that wouldn't load due to system integrity protection, etc. etc. so I had to reinstall the OS from a clean slate a couple of times. Not fun but things are stabilized now. 

I just tried to reinstall Compare Folders on my Mac from the App Store. The problem continues even though it's basically a new Mac. I tried to launch it, App Store says "this app was purchased on another Mac" and asks me to sign in, I enter my password and see the same error in the log:

Service exited with abnormal code: 173

Then App Store asks me to login again, over and over, and the problem happens each time. Very strange.

**Comment by swisspol** [comment] 2017-11-03 14:28
Good news I guess: the update I just submitted to the App Store got rejected because they say the app exits on launch with 173. Looks like the validation code for the App Store receipts which I wrote years ago is not valid anymore.

I suspect that when people do an in-app purchase for the checksum option, the App Store updates the receipt in the app in a way that starts failing validation. I just download the app from the App Store on my development machine and it installs and launches fine.

**Comment by swisspol** [comment] 2017-11-03 14:31
I can now reproduce the problem launching the app Xcode so I'm tracking it down...

**Comment by swisspol** [comment] 2017-11-03 14:58
Actually, to be extra safe: can any of you look up in the Console app for anything printed by Compare Folders when it exits on launch? There should be some actual indication of what fails when verifying the receipt. Thanks

**Comment by duncandisorderly** [comment] 2017-11-03 16:07
![screen shot 2017-11-03 at 16 06 27](https://user-images.githubusercontent.com/33294809/32383866-16d3a36c-c0b1-11e7-93bc-9f881293a574.jpg)

**Comment by swisspol** [comment] 2017-11-03 16:09
Thanks for providing this but what if you search the console for "Compare"? There might be a message from the app higher up.

**Comment by duncandisorderly** [comment] 2017-11-03 16:24
nada. just this.
![screen shot 2017-11-03 at 16 23 25](https://user-images.githubusercontent.com/33294809/32384621-6c58a9fc-c0b3-11e7-98dd-c3a3b002b516.jpg)

**Comment by duncandisorderly** [comment] 2017-11-03 16:36
also, this is weird... it never ungreys & goes to 'open'.

![screen shot 2017-11-03 at 16 35 24](https://user-images.githubusercontent.com/33294809/32385162-250c1d5c-c0b5-11e7-84e9-6a78af406d85.jpg)

**Comment by swisspol** [comment] 2017-11-03 17:02
So I found one problem in the App Store receipt validation code I had for in-app purchases. Looks like the format has changed recently and it breaks that code. I just submitted a new version to Mac App Store with the fix. I have no idea if that will work though...

**Comment by duncandisorderly** [comment] 2017-11-03 17:13
looks the same to me... this is after zapping, restarting & redownloading.

![screen shot 2017-11-03 at 17 12 29](https://user-images.githubusercontent.com/33294809/32386791-4919def0-c0ba-11e7-9fba-5ccfd59a72a4.jpg)

**Comment by swisspol** [comment] 2017-11-04 15:00
Does 1.2.2 now available on App Store fix the issue? You might have to delete the app and reinstall it.

**Comment by duncandisorderly** [comment] 2017-11-04 18:39
that seems to have fixed it, at least on this machine- can't try the laptop until monday. I have it on a third macbook, I think, which I'll try later.... delete, reboot, reinstall, I guess.
still seeing this, which is weird.... there's still something from the mac OS side that's not acknowledging the completeness of the installation.
d.
![screen shot 2017-11-04 at 18 35 53](https://user-images.githubusercontent.com/33294809/32408421-67d5eeda-c18f-11e7-839a-325d98979622.jpg)

**Comment by swisspol** [comment] 2017-11-09 06:06
I’m going to consider this issue solved. Thanks for everyone you help.

**Closed by swisspol** 2017-11-09 06:06 UTC
Labels: bug
